### PR TITLE
[feat][ros2][galactic] Detects ros2 / Galactic Geocholone

### PR DESCRIPTION
**Pull request by teyrana**
@TSC21 

Expanding support for the latest ros2 release ( Galactic Geocholone)

### CODE REVIEW

**Review by TSC21 — COMMENTED** [review]
Thanks! Can you do that for the `build_all` as well?

**Comment by teyrana** [comment]
I don't follow.   is `build_all` a branch?

**Comment by TSC21** [comment]
> I don't follow. is `build_all` a branch?

https://github.com/PX4/px4_ros_com/blob/master/scripts/build_all.bash

**Comment by TSC21** [comment]
Bringing this in, I update it in the other script myself. Thanks

**Pull request merged**
