### PR TITLE
Modified Python offboard control example to support ROS2 Humble

### PR DESCRIPTION
**Pull request by nikhilsnayak3473**
- Added **/fmu/out/vehicle_local_position** and **/fmu/out/vehicle_status** subscribers to establish a closed loop control mechanism.
- Implemented a proper QoS profile as supported by ROS2 Humble for reliable communication.
- Updated the code to enable the vehicle to take off to a height of 5 meters in offboard mode and perform a controlled landing at the same position.

### CODE REVIEW

**Review by beniaminopozzan — COMMENTED** [review]
Thanks @nikhilsnayak3473 !
I tested it on Humble and on Foxy and I saw no issue.

Could you also update `CMakeLists.txt` and `package.xml` such that the python example could be run with
```sh
ros2 run px4_ros_com offboard_control.py
```
?

**Comment by nikhilsnayak3473** [comment]
Sure I'll do it

**Comment by nikhilsnayak3473** [comment]
I have another example in which a list of setpoints can be given as command line arg and the drone will navigate to all the set points and land. I will add that example in this commit. If you find it useful add it to the examples @beniaminopozzan

**Comment by nikhilsnayak3473** [comment]
> Thanks @nikhilsnayak3473 ! I tested it on Humble and on Foxy and I saw no issue.
> 
> Could you also update `CMakeLists.txt` and `package.xml` such that the python example could be run with
> 
> ```shell
> ros2 run px4_ros_com offboard_control.py
> ```
> 
> ?

Hello @beniaminopozzan, Since I am not familiar with working with cpp packages of ROS2, I am unable to add the node as an executable using **ros2 run**. If you could breif me about the procedure to add a python node as executable from from a cpp package or if you can share any resource regarding this, it would be more helpful for me complete the said changes ASAP.
Thank You!!

**Comment by beniaminopozzan** [comment]
Hi @nikhilsnayak3473 , I'm going to merge this as it is, I'll take care of the `ros run` part later!

Thank you!

**Pull request merged**
